import { useEffect, useMemo, useRef, useState } from 'react'
import SlideRenderer from '../slides/SlideRenderer'
import TeacherAvatar, { type AvatarState } from '../avatar/TeacherAvatar'
import PopQuizPanel from '../quiz/PopQuizPanel'
import SageDoubtPanel from '../sage/SageDoubtPanel'
import { useSpeech } from '../../hooks/useSpeech'
import type { CurrentStateResponse } from '../../types/api.types'

interface ClassroomLayoutProps {
  currentState: CurrentStateResponse
  onAdvance: () => Promise<void>
  onSubmitPrediction: (predictionText: string) => Promise<void>
  onQuizSubmit: (questionId: string, selectedOptionId: string) => Promise<import('../../types/api.types').QuizAttemptResponse>
  onOpenSage: () => Promise<string>
  onAskSage: (message: string) => Promise<import('../../types/api.types').DoubtMessageResponse>
  onCloseSage: () => Promise<void>
  onSkipDoubts: () => Promise<void>
}

export default function ClassroomLayout({
  currentState,
  onAdvance,
  onSubmitPrediction,
  onQuizSubmit,
  onOpenSage,
  onAskSage,
  onCloseSage,
  onSkipDoubts,
}: ClassroomLayoutProps) {
  const [predictionText, setPredictionText] = useState('')
  const [showSagePanel, setShowSagePanel] = useState(false)
  const [doubtSessionId, setDoubtSessionId] = useState<string | null>(null)
  const [currentSlideIndex, setCurrentSlideIndex] = useState(0)
  const [speechEnabled, setSpeechEnabled] = useState(false)
  const pendingSpeakAfterAdvanceRef = useRef(false)

  const { speechStatus, speechError, speakNow, warmUp, isSupported } = useSpeech()

  const slides = currentState.content.slides
  const currentSlide = slides[currentSlideIndex]
  const stateType = currentState.current_state?.state_type
  const explanationText = currentSlide?.explanation?.explanation_text ?? ''

  const avatarCaption = useMemo(() => {
    if (explanationText.trim() !== '') {
      return explanationText
    }
    return currentState.current_state?.label ?? ''
  }, [explanationText, currentState.current_state?.label])

  useEffect(() => {
    setCurrentSlideIndex(0)
  }, [currentState.current_state?.state_id])

  useEffect(() => {
    if (!speechEnabled || !pendingSpeakAfterAdvanceRef.current) {
      return
    }
    pendingSpeakAfterAdvanceRef.current = false
    if (explanationText.trim() !== '') {
      speakNow(explanationText)
    }
  }, [currentState.current_state?.state_id, explanationText, speechEnabled, speakNow])

  const handleEnableSpeech = async () => {
    warmUp()
    setSpeechEnabled(true)
    if (explanationText.trim() !== '') {
      await speakNow(explanationText)
      return
    }
    await speakNow('Teacher voice is enabled. Click Continue to hear the lesson.')
  }

  const speakSlideExplanation = async (slideIndex: number) => {
    if (!speechEnabled) {
      return
    }
    const slideExplanation = slides[slideIndex]?.explanation?.explanation_text ?? ''
    if (slideExplanation.trim() !== '') {
      await speakNow(slideExplanation)
    }
  }

  const handleContinue = async () => {
    if (!speechEnabled) {
      await handleEnableSpeech()
      return
    }

    if (stateType === 'student_predict') {
      await onSubmitPrediction(predictionText)
      setPredictionText('')
      pendingSpeakAfterAdvanceRef.current = true
      return
    }

    if (currentSlideIndex + 1 < slides.length) {
      const nextSlideIndex = currentSlideIndex + 1
      setCurrentSlideIndex(nextSlideIndex)
      await speakSlideExplanation(nextSlideIndex)
      return
    }

    pendingSpeakAfterAdvanceRef.current = true
    await onAdvance()
  }

  const openSage = async () => {
    warmUp()
    setSpeechEnabled(true)
    const sessionId = await onOpenSage()
    setDoubtSessionId(sessionId)
    setShowSagePanel(true)
  }

  const resolvedAvatarState: AvatarState =
    currentState.session_status === 'completed'
      ? 'idle'
      : stateType === 'pop_quiz'
      ? 'questioning'
      : stateType === 'student_predict' || showSagePanel
        ? 'listening'
        : speechStatus === 'speaking'
          ? 'speaking'
          : 'idle'

  return (
    <div className="classroom-layout">
      {!speechEnabled && isSupported ? (
        <div className="speech-unlock-banner card">
          <p>
            Click below to enable the teacher&apos;s voice. Audio is generated by the server and works in Brave.
          </p>
          <button type="button" className="btn btn-primary" onClick={handleEnableSpeech}>
            Enable Teacher Voice
          </button>
        </div>
      ) : null}
      {!isSupported ? (
        <div className="speech-unlock-banner card">
          <p>Your browser does not support text-to-speech. Read the explanation below the avatar.</p>
        </div>
      ) : null}
      {speechError !== null ? (
        <div className="error-banner speech-error-banner">{speechError}</div>
      ) : null}
      <section className="slide-area card">
        {currentState.session_status === 'completed' ? (
          <div className="session-complete-panel">
            <h2>Class complete</h2>
            <p>You have finished all topics in this class.</p>
          </div>
        ) : (
          <>
        <div className="state-label">{currentState.current_state?.label}</div>
        {stateType === 'pop_quiz' ? (
          <PopQuizPanel
            questions={currentState.content.quiz_questions}
            onSubmit={onQuizSubmit}
            onComplete={onAdvance}
          />
        ) : stateType === 'student_predict' ? (
          <div className="predict-panel">
            <SlideRenderer elements={currentSlide?.elements ?? []} />
            <textarea
              className="textarea"
              placeholder="Share your prediction..."
              value={predictionText}
              onChange={(event) => setPredictionText(event.target.value)}
            />
          </div>
        ) : (
          <SlideRenderer elements={currentSlide?.elements ?? []} />
        )}
        <div className="classroom-controls">
          {stateType !== 'pop_quiz' && stateType !== 'doubts_resolution' ? (
            <button type="button" className="btn btn-primary" onClick={handleContinue}>
              {speechEnabled ? 'Continue' : 'Enable voice & continue'}
            </button>
          ) : null}
          {stateType === 'doubts_resolution' ? (
            <>
              <button type="button" className="btn btn-sage" onClick={openSage}>Ask SAGE</button>
              <button
                type="button"
                className="btn btn-secondary"
                onClick={async () => {
                  setShowSagePanel(false)
                  setDoubtSessionId(null)
                  await onSkipDoubts()
                }}
              >
                Skip to next topic
              </button>
            </>
          ) : null}
        </div>
          </>
        )}
      </section>
      <aside className="avatar-area card">
        <TeacherAvatar state={resolvedAvatarState} caption={avatarCaption} />
        {explanationText.trim() !== '' ? (
          <button
            type="button"
            className="btn btn-secondary replay-btn"
            onClick={async () => {
              warmUp()
              setSpeechEnabled(true)
              await speakNow(explanationText)
            }}
          >
            Replay explanation
          </button>
        ) : null}
      </aside>
      {showSagePanel && doubtSessionId !== null ? (
        <SageDoubtPanel
          onAsk={onAskSage}
          onClose={async () => {
            await onCloseSage()
            setShowSagePanel(false)
          }}
        />
      ) : null}
      <style>{`
        .classroom-layout { display: grid; grid-template-columns: 2fr 1fr; gap: 1rem; min-height: calc(100vh - 120px); }
        .speech-unlock-banner { grid-column: 1 / -1; padding: 1rem 1.25rem; display: flex; align-items: center; justify-content: space-between; gap: 1rem; flex-wrap: wrap; background: #eff6ff; border-color: #bfdbfe; }
        .speech-error-banner { grid-column: 1 / -1; }
        .slide-area, .avatar-area { padding: 1.25rem; }
        .avatar-area { display: flex; flex-direction: column; align-items: center; gap: 1rem; }
        .replay-btn { width: 100%; }
        .state-label { color: var(--teach-muted); margin-bottom: 1rem; font-weight: 600; }
        .classroom-controls { display: flex; gap: 0.75rem; margin-top: 1rem; flex-wrap: wrap; }
        .predict-panel { display: flex; flex-direction: column; gap: 0.75rem; }
        .session-complete-panel { padding: 2rem 1rem; text-align: center; }
        .session-complete-panel h2 { margin-bottom: 0.5rem; }
        @media (max-width: 900px) {
          .classroom-layout { grid-template-columns: 1fr; }
        }
      `}</style>
    </div>
  )
}
