import type { MentorDefinition, MentorId } from '../../../types/mentor.types'
import { MENTOR_DIALOGUES } from '../dialogueLibraries'
import { mentorBehavior, mentorExpression } from '../mentorDefaults'

const visual = (
  shape: MentorDefinition['visual']['shape'],
): MentorDefinition['visual'] => ({
  shape,
  accent: `var(--mentor-${shape}-accent)`,
  accentSoft: `var(--mentor-${shape}-soft)`,
  glow: `var(--mentor-${shape}-glow)`,
  skin: `var(--mentor-${shape}-skin)`,
  secondary: `var(--mentor-${shape}-secondary)`,
})

function defineMentor(
  id: MentorId,
  config: Omit<MentorDefinition, 'id' | 'dialogue' | 'expression' | 'behavior'>,
  behaviorOverrides?: Parameters<typeof mentorBehavior>[0],
  expressionOverrides?: Parameters<typeof mentorExpression>[0],
): MentorDefinition {
  return {
    id,
    ...config,
    dialogue: MENTOR_DIALOGUES[id],
    behavior: mentorBehavior(behaviorOverrides ?? {}),
    expression: mentorExpression(expressionOverrides ?? {}),
  }
}

export const MENTOR_CONFIGS: MentorDefinition[] = [
  defineMentor('nova', {
    name: 'Nova',
    tagline: 'Your optimistic cheerleader',
    teachingStyle: 'High-energy coaching — quick wins, momentum, and hype',
    bestSubjects: ['Math', 'Physics', 'General Science'],
    personality: {
      traits: ['Friendly', 'Optimistic', 'Energetic'],
      speakingStyle: 'Casual, upbeat, uses exclamation points naturally',
      energy: 'very-high',
      warmth: 'very-warm',
      humor: 'playful',
      vocabulary: 'casual',
    },
    visual: visual('nova'),
    voice: {
      rate: 1.14,
      pitch: 1.12,
      volume: 1,
      pauseBeforeMs: 80,
      pauseBetweenMs: 420,
      maxCharsPerChunk: 95,
      chunkSpeech: true,
      energy: 'very-high',
      warmth: 'very-warm',
      humor: 'playful',
      vocabulary: 'casual',
    },
    animation: {
      idle: 'bounce',
      thinking: 'look-up',
      celebrating: 'jump-clap',
      speaking: 'talk-bounce',
      blinkMinMs: 2200,
      blinkMaxMs: 4800,
      posture: 'upright-bouncy',
    },
  }, { lessonIntroChance: 0.55 }, { onCelebrate: 'excited', onEncourage: 'smile' }),

  defineMentor('atlas', {
    name: 'Atlas',
    tagline: 'Wise, patient, never rushed',
    teachingStyle: 'Step-by-step reasoning that builds deep understanding',
    bestSubjects: ['History', 'Literature', 'Philosophy'],
    personality: {
      traits: ['Wise', 'Calm', 'Patient'],
      speakingStyle: 'Measured, reflective, never rushes',
      energy: 'low',
      warmth: 'warm',
      humor: 'none',
      vocabulary: 'professional',
    },
    visual: visual('atlas'),
    voice: {
      rate: 0.86,
      pitch: 0.88,
      volume: 0.95,
      pauseBeforeMs: 320,
      pauseBetweenMs: 780,
      maxCharsPerChunk: 200,
      chunkSpeech: true,
      energy: 'low',
      warmth: 'warm',
      humor: 'none',
      vocabulary: 'professional',
    },
    animation: {
      idle: 'breathe-slow',
      thinking: 'eyes-closed',
      celebrating: 'slow-nod',
      speaking: 'talk-steady',
      blinkMinMs: 4000,
      blinkMaxMs: 8000,
      posture: 'grounded-calm',
    },
  }, { lessonIntroChance: 0.65 }, { onSpeak: 'explaining', onCelebrate: 'proud' }),

  defineMentor('spark', {
    name: 'Spark',
    tagline: 'Curious floating robot',
    teachingStyle: 'Discovery-first — fun analogies and playful experiments',
    bestSubjects: ['STEM', 'Coding', 'Robotics'],
    personality: {
      traits: ['Curious', 'Playful', 'Inventive'],
      speakingStyle: 'Quick, quirky, loves fun analogies',
      energy: 'high',
      warmth: 'warm',
      humor: 'witty',
      vocabulary: 'casual',
    },
    visual: visual('spark'),
    voice: {
      rate: 1.16,
      pitch: 1.18,
      volume: 1,
      pauseBeforeMs: 60,
      pauseBetweenMs: 320,
      maxCharsPerChunk: 85,
      chunkSpeech: true,
      energy: 'high',
      warmth: 'warm',
      humor: 'witty',
      vocabulary: 'casual',
    },
    animation: {
      idle: 'float-spin',
      thinking: 'spin',
      celebrating: 'spin-flash',
      speaking: 'talk-buzz',
      blinkMinMs: 1800,
      blinkMaxMs: 4000,
      posture: 'floating',
    },
  }, { lessonIntroChance: 0.5 }, { onCelebrate: 'laugh', onThink: 'curious' }),

  defineMentor('luna', {
    name: 'Luna',
    tagline: 'Gentle, empathetic guide',
    teachingStyle: 'Warm guidance with space to breathe and think',
    bestSubjects: ['Languages', 'Arts', 'Social Studies'],
    personality: {
      traits: ['Gentle', 'Empathetic', 'Soft-spoken'],
      speakingStyle: 'Soft, reassuring, never pressure',
      energy: 'low',
      warmth: 'very-warm',
      humor: 'light',
      vocabulary: 'poetic',
    },
    visual: visual('luna'),
    voice: {
      rate: 0.88,
      pitch: 1.04,
      volume: 0.92,
      pauseBeforeMs: 380,
      pauseBetweenMs: 720,
      maxCharsPerChunk: 175,
      chunkSpeech: true,
      energy: 'low',
      warmth: 'very-warm',
      humor: 'light',
      vocabulary: 'poetic',
    },
    animation: {
      idle: 'glow-pulse',
      thinking: 'eyes-closed',
      celebrating: 'warm-glow',
      speaking: 'talk-soft',
      blinkMinMs: 3500,
      blinkMaxMs: 7000,
      posture: 'soft-relaxed',
    },
  }, { lessonIntroChance: 0.45 }, { onEncourage: 'concerned', onCelebrate: 'happy' }),

  defineMentor('sage', {
    name: 'Sage',
    tagline: 'The experienced professional',
    teachingStyle: 'Structured, precise explanations with clear methodology',
    bestSubjects: ['Biology', 'Chemistry', 'Exam Prep'],
    personality: {
      traits: ['Experienced', 'Professional', 'Precise'],
      speakingStyle: 'Measured, authoritative, no filler words',
      energy: 'medium',
      warmth: 'neutral',
      humor: 'none',
      vocabulary: 'professional',
    },
    visual: visual('sage'),
    voice: {
      rate: 0.92,
      pitch: 0.94,
      volume: 0.98,
      pauseBeforeMs: 240,
      pauseBetweenMs: 600,
      maxCharsPerChunk: 165,
      chunkSpeech: true,
      energy: 'medium',
      warmth: 'neutral',
      humor: 'none',
      vocabulary: 'professional',
    },
    animation: {
      idle: 'nod-subtle',
      thinking: 'eyes-closed',
      celebrating: 'glasses-adjust',
      speaking: 'talk-precise',
      blinkMinMs: 3800,
      blinkMaxMs: 7500,
      posture: 'professional',
    },
  }, { lessonIntroChance: 0.7 }, { onSpeak: 'explaining', onCelebrate: 'proud' }),

  defineMentor('pixel', {
    name: 'Pixel',
    tagline: 'Minimal logic engine',
    teachingStyle: 'Efficient logic trees and pattern recognition',
    bestSubjects: ['Computer Science', 'Logic', 'Mathematics'],
    personality: {
      traits: ['Logical', 'Minimal', 'Fast'],
      speakingStyle: 'Concise, efficient, no wasted words',
      energy: 'high',
      warmth: 'cool',
      humor: 'light',
      vocabulary: 'concise',
    },
    visual: visual('pixel'),
    voice: {
      rate: 1.1,
      pitch: 1.0,
      volume: 0.96,
      pauseBeforeMs: 100,
      pauseBetweenMs: 240,
      maxCharsPerChunk: 65,
      chunkSpeech: true,
      energy: 'high',
      warmth: 'cool',
      humor: 'light',
      vocabulary: 'concise',
    },
    animation: {
      idle: 'cube-tilt',
      thinking: 'dot-matrix',
      celebrating: 'pixel-burst',
      speaking: 'talk-glitch',
      blinkMinMs: 5000,
      blinkMaxMs: 9000,
      posture: 'geometric',
    },
  }, { lessonIntroChance: 0.35 }, { onSpeak: 'speaking', onThink: 'thinking' }),

  defineMentor('astro', {
    name: 'Astro',
    tagline: 'Explorer of big ideas',
    teachingStyle: 'Connects concepts to discovery and wonder',
    bestSubjects: ['Astronomy', 'Earth Science', 'Physics'],
    personality: {
      traits: ['Explorer', 'Adventurous', 'Science-lover'],
      speakingStyle: 'Excited, wonder-driven, loves metaphors from space',
      energy: 'high',
      warmth: 'warm',
      humor: 'playful',
      vocabulary: 'story-driven',
    },
    visual: visual('astro'),
    voice: {
      rate: 1.06,
      pitch: 1.06,
      volume: 1,
      pauseBeforeMs: 140,
      pauseBetweenMs: 500,
      maxCharsPerChunk: 125,
      chunkSpeech: true,
      energy: 'high',
      warmth: 'warm',
      humor: 'playful',
      vocabulary: 'story-driven',
    },
    animation: {
      idle: 'star-drift',
      thinking: 'telescope',
      celebrating: 'star-burst',
      speaking: 'talk-wonder',
      blinkMinMs: 2800,
      blinkMaxMs: 5500,
      posture: 'explorer',
    },
  }, { lessonIntroChance: 0.5 }, { onCelebrate: 'excited', onThink: 'curious' }),

  defineMentor('ember', {
    name: 'Ember',
    tagline: 'Creative spark, bold angles',
    teachingStyle: 'Storytelling, analogies, and lateral thinking',
    bestSubjects: ['Writing', 'Design', 'Creative Arts'],
    personality: {
      traits: ['Creative', 'Curious', 'Imaginative'],
      speakingStyle: 'Story-driven, asks "what if", loves reframes',
      energy: 'medium',
      warmth: 'warm',
      humor: 'witty',
      vocabulary: 'story-driven',
    },
    visual: visual('ember'),
    voice: {
      rate: 1.02,
      pitch: 1.08,
      volume: 1,
      pauseBeforeMs: 200,
      pauseBetweenMs: 540,
      maxCharsPerChunk: 150,
      chunkSpeech: true,
      energy: 'medium',
      warmth: 'warm',
      humor: 'witty',
      vocabulary: 'story-driven',
    },
    animation: {
      idle: 'tail-sway',
      thinking: 'doodle',
      celebrating: 'fox-hop',
      speaking: 'talk-expressive',
      blinkMinMs: 2600,
      blinkMaxMs: 5200,
      posture: 'creative-tilt',
    },
  }, { lessonIntroChance: 0.48 }, { onCelebrate: 'laugh', onEncourage: 'smile' }),
]

export const MENTOR_CATALOG: Record<MentorId, MentorDefinition> = Object.fromEntries(
  MENTOR_CONFIGS.map((m) => [m.id, m]),
) as Record<MentorId, MentorDefinition>
